version: "3.4"

services:
  web:
    image: nginx:latest
    container_name: "test"
    ports:
      - "80:80"
    volumes:
      - ../:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    links:
      - redis
      - database
      - php

  php:
    build: .
    image: "test/php"
    container_name: "test-backend"
    volumes:
      - ../:/var/www
      - ./logs/php/profiler:/profiler
    links:
      - redis
      - database

  database:
    image: mysql:8.0.22
    ports:
      - "3006:3306"
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=test
    container_name: "test-database"

  redis:
    image: "redis:alpine"
    container_name: "test-redis"
    ports:
      - "6079:6379"

volumes:
  db-volume:
    name: test-db-volume
